# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cuadc_vision/MissionStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MissionStatus(genpy.Message):
  _md5sum = "42a0745a697dd6adddaac7f2c09f5f59"
  _type = "cuadc_vision/MissionStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# MissionStatus.msg — main.py → detector_node 任务状态同步
#
# 用于 detector_node 在画面上显示弹药、瞄准、抛投等任务状态信息。

uint8 ammo_a                # 前抛投器 (A) 剩余弹药数，0 表示无/未挂载
uint8 ammo_b                # 后抛投器 (B) 剩余弹药数，0 表示无/未挂载
bool aiming                 # 飞控处于 GUIDED 模式且正在执行对准任务
string last_drop            # 最近一次抛投的抛投器编号 ("A" / "B" / "")
"""
  __slots__ = ['ammo_a','ammo_b','aiming','last_drop']
  _slot_types = ['uint8','uint8','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ammo_a,ammo_b,aiming,last_drop

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ammo_a is None:
        self.ammo_a = 0
      if self.ammo_b is None:
        self.ammo_b = 0
      if self.aiming is None:
        self.aiming = False
      if self.last_drop is None:
        self.last_drop = ''
    else:
      self.ammo_a = 0
      self.ammo_b = 0
      self.aiming = False
      self.last_drop = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.ammo_a, _x.ammo_b, _x.aiming))
      _x = self.last_drop
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ammo_a, _x.ammo_b, _x.aiming,) = _get_struct_3B().unpack(str[start:end])
      self.aiming = bool(self.aiming)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_drop = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_drop = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.ammo_a, _x.ammo_b, _x.aiming))
      _x = self.last_drop
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.ammo_a, _x.ammo_b, _x.aiming,) = _get_struct_3B().unpack(str[start:end])
      self.aiming = bool(self.aiming)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_drop = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_drop = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
