set(_CATKIN_CURRENT_PACKAGE "cuadc_vision")
set(cuadc_vision_VERSION "1.0.0")
set(cuadc_vision_MAINTAINER "CUADC Vision Team <cuadc@example.com>")
set(cuadc_vision_PACKAGE_FORMAT "2")
set(cuadc_vision_BUILD_DEPENDS "message_generation" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "tf2_ros" "tf2_geometry_msgs" "mavros_msgs")
set(cuadc_vision_BUILD_EXPORT_DEPENDS "message_runtime")
set(cuadc_vision_BUILDTOOL_DEPENDS "catkin")
set(cuadc_vision_BUILDTOOL_EXPORT_DEPENDS )
set(cuadc_vision_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "tf2_ros" "tf2_geometry_msgs" "mavros_msgs")
set(cuadc_vision_RUN_DEPENDS "message_runtime" "rospy" "std_msgs" "sensor_msgs" "geometry_msgs" "cv_bridge" "image_transport" "tf2_ros" "tf2_geometry_msgs" "mavros_msgs")
set(cuadc_vision_TEST_DEPENDS )
set(cuadc_vision_DOC_DEPENDS )
set(cuadc_vision_URL_WEBSITE "")
set(cuadc_vision_URL_BUGTRACKER "")
set(cuadc_vision_URL_REPOSITORY "")
set(cuadc_vision_DEPRECATED "")