(cl:in-package cuadc_vision-msg)
(cl:export '(HEADER-VAL
          HEADER
          COUNT-VAL
          COUNT
          VALID-VAL
          VALID
          BUCKET_CENTER_X-VAL
          BUCKET_CENTER_X
          BUCKET_CENTER_Y-VAL
          BUCKET_CENTER_Y
          A_AIM_X-VAL
          A_AIM_X
          A_AIM_Y-VAL
          A_AIM_Y
          B_AIM_X-VAL
          B_AIM_X
          B_AIM_Y-VAL
          B_AIM_Y
          A_DELTA_X_PX-VAL
          A_DELTA_X_PX
          A_DELTA_Y_PX-VAL
          A_DELTA_Y_PX
          B_DELTA_X_PX-VAL
          B_DELTA_X_PX
          B_DELTA_Y_PX-VAL
          B_DELTA_Y_PX
          A_DELTA_X_M-VAL
          A_DELTA_X_M
          A_DELTA_Y_M-VAL
          A_DELTA_Y_M
          B_DELTA_X_M-VAL
          B_DELTA_X_M
          B_DELTA_Y_M-VAL
          B_DELTA_Y_M
          A_NED_VALID-VAL
          A_NED_VALID
          A_NED_N-VAL
          A_NED_N
          A_NED_E-VAL
          A_NED_E
          A_NED_D-VAL
          A_NED_D
          B_NED_VALID-VAL
          B_NED_VALID
          B_NED_N-VAL
          B_NED_N
          B_NED_E-VAL
          B_NED_E
          B_NED_D-VAL
          B_NED_D
          CONFIDENCE-VAL
          CONFIDENCE
          SOURCE_CLASS-VAL
          SOURCE_CLASS
))