# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from d435i_yellow_circle_detector/GeoTarget.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class GeoTarget(genpy.Message):
  _md5sum = "97435bcc3e1e35e6ba97ca5a2f45aeba"
  _type = "d435i_yellow_circle_detector/GeoTarget"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool valid
string status
string source_topic
string class_name
float32 confidence
int32 center_x
int32 center_y
float32 camera_x_m
float32 camera_y_m
float32 camera_z_m
float32 body_x_m
float32 body_y_m
float32 body_z_m
float32 enu_east_m
float32 enu_north_m
float32 enu_up_m
float64 latitude
float64 longitude
float64 altitude

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','valid','status','source_topic','class_name','confidence','center_x','center_y','camera_x_m','camera_y_m','camera_z_m','body_x_m','body_y_m','body_z_m','enu_east_m','enu_north_m','enu_up_m','latitude','longitude','altitude']
  _slot_types = ['std_msgs/Header','bool','string','string','string','float32','int32','int32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,valid,status,source_topic,class_name,confidence,center_x,center_y,camera_x_m,camera_y_m,camera_z_m,body_x_m,body_y_m,body_z_m,enu_east_m,enu_north_m,enu_up_m,latitude,longitude,altitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GeoTarget, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.valid is None:
        self.valid = False
      if self.status is None:
        self.status = ''
      if self.source_topic is None:
        self.source_topic = ''
      if self.class_name is None:
        self.class_name = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.camera_x_m is None:
        self.camera_x_m = 0.
      if self.camera_y_m is None:
        self.camera_y_m = 0.
      if self.camera_z_m is None:
        self.camera_z_m = 0.
      if self.body_x_m is None:
        self.body_x_m = 0.
      if self.body_y_m is None:
        self.body_y_m = 0.
      if self.body_z_m is None:
        self.body_z_m = 0.
      if self.enu_east_m is None:
        self.enu_east_m = 0.
      if self.enu_north_m is None:
        self.enu_north_m = 0.
      if self.enu_up_m is None:
        self.enu_up_m = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.valid = False
      self.status = ''
      self.source_topic = ''
      self.class_name = ''
      self.confidence = 0.
      self.center_x = 0
      self.center_y = 0
      self.camera_x_m = 0.
      self.camera_y_m = 0.
      self.camera_z_m = 0.
      self.body_x_m = 0.
      self.body_y_m = 0.
      self.body_z_m = 0.
      self.enu_east_m = 0.
      self.enu_north_m = 0.
      self.enu_up_m = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.source_topic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2i9f3d().pack(_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.enu_east_m, _x.enu_north_m, _x.enu_up_m, _x.latitude, _x.longitude, _x.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_topic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_topic = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.enu_east_m, _x.enu_north_m, _x.enu_up_m, _x.latitude, _x.longitude, _x.altitude,) = _get_struct_f2i9f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.source_topic
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2i9f3d().pack(_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.enu_east_m, _x.enu_north_m, _x.enu_up_m, _x.latitude, _x.longitude, _x.altitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_topic = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_topic = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.enu_east_m, _x.enu_north_m, _x.enu_up_m, _x.latitude, _x.longitude, _x.altitude,) = _get_struct_f2i9f3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_f2i9f3d = None
def _get_struct_f2i9f3d():
    global _struct_f2i9f3d
    if _struct_f2i9f3d is None:
        _struct_f2i9f3d = struct.Struct("<f2i9f3d")
    return _struct_f2i9f3d
