# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from d435i_yellow_circle_detector/MissionTarget.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MissionTarget(genpy.Message):
  _md5sum = "9e275971ddc71593e97b9bdc197f8cad"
  _type = "d435i_yellow_circle_detector/MissionTarget"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool valid
string mission_stage
string target_type
string class_name
float32 confidence
int32 center_x
int32 center_y
float32 camera_x_m
float32 camera_y_m
float32 camera_z_m
float32 distance_m
float32 bbox_width_m
float32 bbox_height_m
float32 nominal_diameter_m
string diameter_class
string zone_hint
float32 a_zone_radius_m
float32 b_zone_radius_m
string action_hint

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','valid','mission_stage','target_type','class_name','confidence','center_x','center_y','camera_x_m','camera_y_m','camera_z_m','distance_m','bbox_width_m','bbox_height_m','nominal_diameter_m','diameter_class','zone_hint','a_zone_radius_m','b_zone_radius_m','action_hint']
  _slot_types = ['std_msgs/Header','bool','string','string','string','float32','int32','int32','float32','float32','float32','float32','float32','float32','float32','string','string','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,valid,mission_stage,target_type,class_name,confidence,center_x,center_y,camera_x_m,camera_y_m,camera_z_m,distance_m,bbox_width_m,bbox_height_m,nominal_diameter_m,diameter_class,zone_hint,a_zone_radius_m,b_zone_radius_m,action_hint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionTarget, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.valid is None:
        self.valid = False
      if self.mission_stage is None:
        self.mission_stage = ''
      if self.target_type is None:
        self.target_type = ''
      if self.class_name is None:
        self.class_name = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.camera_x_m is None:
        self.camera_x_m = 0.
      if self.camera_y_m is None:
        self.camera_y_m = 0.
      if self.camera_z_m is None:
        self.camera_z_m = 0.
      if self.distance_m is None:
        self.distance_m = 0.
      if self.bbox_width_m is None:
        self.bbox_width_m = 0.
      if self.bbox_height_m is None:
        self.bbox_height_m = 0.
      if self.nominal_diameter_m is None:
        self.nominal_diameter_m = 0.
      if self.diameter_class is None:
        self.diameter_class = ''
      if self.zone_hint is None:
        self.zone_hint = ''
      if self.a_zone_radius_m is None:
        self.a_zone_radius_m = 0.
      if self.b_zone_radius_m is None:
        self.b_zone_radius_m = 0.
      if self.action_hint is None:
        self.action_hint = ''
    else:
      self.header = std_msgs.msg.Header()
      self.valid = False
      self.mission_stage = ''
      self.target_type = ''
      self.class_name = ''
      self.confidence = 0.
      self.center_x = 0
      self.center_y = 0
      self.camera_x_m = 0.
      self.camera_y_m = 0.
      self.camera_z_m = 0.
      self.distance_m = 0.
      self.bbox_width_m = 0.
      self.bbox_height_m = 0.
      self.nominal_diameter_m = 0.
      self.diameter_class = ''
      self.zone_hint = ''
      self.a_zone_radius_m = 0.
      self.b_zone_radius_m = 0.
      self.action_hint = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.mission_stage
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2i7f().pack(_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m, _x.nominal_diameter_m))
      _x = self.diameter_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.zone_hint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.a_zone_radius_m, _x.b_zone_radius_m))
      _x = self.action_hint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mission_stage = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mission_stage = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m, _x.nominal_diameter_m,) = _get_struct_f2i7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.diameter_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.diameter_class = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.zone_hint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.zone_hint = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.a_zone_radius_m, _x.b_zone_radius_m,) = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_hint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_hint = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.mission_stage
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.target_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2i7f().pack(_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m, _x.nominal_diameter_m))
      _x = self.diameter_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.zone_hint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.a_zone_radius_m, _x.b_zone_radius_m))
      _x = self.action_hint
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.valid,) = _get_struct_B().unpack(str[start:end])
      self.valid = bool(self.valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mission_stage = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mission_stage = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.target_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.target_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.confidence, _x.center_x, _x.center_y, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m, _x.nominal_diameter_m,) = _get_struct_f2i7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.diameter_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.diameter_class = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.zone_hint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.zone_hint = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.a_zone_radius_m, _x.b_zone_radius_m,) = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_hint = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_hint = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_f2i7f = None
def _get_struct_f2i7f():
    global _struct_f2i7f
    if _struct_f2i7f is None:
        _struct_f2i7f = struct.Struct("<f2i7f")
    return _struct_f2i7f
