# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from d435i_yellow_circle_detector/YellowCircle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class YellowCircle(genpy.Message):
  _md5sum = "546a21369cee59d7afb5df9576c1da21"
  _type = "d435i_yellow_circle_detector/YellowCircle"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool detected
int32 x
int32 y
float32 radius
float32 area
float32 depth_m
float32 raw_depth_m
float32 diameter_depth_m
float32 calibrated_depth_m
string depth_source
float32 center_offset_x
float32 center_offset_y
bool position_valid
float32 camera_x_m
float32 camera_y_m
float32 camera_z_m
float32 distance_m
float32 body_x_m
float32 body_y_m
float32 body_z_m
float32 body_distance_m

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','detected','x','y','radius','area','depth_m','raw_depth_m','diameter_depth_m','calibrated_depth_m','depth_source','center_offset_x','center_offset_y','position_valid','camera_x_m','camera_y_m','camera_z_m','distance_m','body_x_m','body_y_m','body_z_m','body_distance_m']
  _slot_types = ['std_msgs/Header','bool','int32','int32','float32','float32','float32','float32','float32','float32','string','float32','float32','bool','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,detected,x,y,radius,area,depth_m,raw_depth_m,diameter_depth_m,calibrated_depth_m,depth_source,center_offset_x,center_offset_y,position_valid,camera_x_m,camera_y_m,camera_z_m,distance_m,body_x_m,body_y_m,body_z_m,body_distance_m

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YellowCircle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected is None:
        self.detected = False
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.radius is None:
        self.radius = 0.
      if self.area is None:
        self.area = 0.
      if self.depth_m is None:
        self.depth_m = 0.
      if self.raw_depth_m is None:
        self.raw_depth_m = 0.
      if self.diameter_depth_m is None:
        self.diameter_depth_m = 0.
      if self.calibrated_depth_m is None:
        self.calibrated_depth_m = 0.
      if self.depth_source is None:
        self.depth_source = ''
      if self.center_offset_x is None:
        self.center_offset_x = 0.
      if self.center_offset_y is None:
        self.center_offset_y = 0.
      if self.position_valid is None:
        self.position_valid = False
      if self.camera_x_m is None:
        self.camera_x_m = 0.
      if self.camera_y_m is None:
        self.camera_y_m = 0.
      if self.camera_z_m is None:
        self.camera_z_m = 0.
      if self.distance_m is None:
        self.distance_m = 0.
      if self.body_x_m is None:
        self.body_x_m = 0.
      if self.body_y_m is None:
        self.body_y_m = 0.
      if self.body_z_m is None:
        self.body_z_m = 0.
      if self.body_distance_m is None:
        self.body_distance_m = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.detected = False
      self.x = 0
      self.y = 0
      self.radius = 0.
      self.area = 0.
      self.depth_m = 0.
      self.raw_depth_m = 0.
      self.diameter_depth_m = 0.
      self.calibrated_depth_m = 0.
      self.depth_source = ''
      self.center_offset_x = 0.
      self.center_offset_y = 0.
      self.position_valid = False
      self.camera_x_m = 0.
      self.camera_y_m = 0.
      self.camera_z_m = 0.
      self.distance_m = 0.
      self.body_x_m = 0.
      self.body_y_m = 0.
      self.body_z_m = 0.
      self.body_distance_m = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2i6f().pack(_x.detected, _x.x, _x.y, _x.radius, _x.area, _x.depth_m, _x.raw_depth_m, _x.diameter_depth_m, _x.calibrated_depth_m))
      _x = self.depth_source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fB8f().pack(_x.center_offset_x, _x.center_offset_y, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.body_distance_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.detected, _x.x, _x.y, _x.radius, _x.area, _x.depth_m, _x.raw_depth_m, _x.diameter_depth_m, _x.calibrated_depth_m,) = _get_struct_B2i6f().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.depth_source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.depth_source = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.center_offset_x, _x.center_offset_y, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.body_distance_m,) = _get_struct_2fB8f().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B2i6f().pack(_x.detected, _x.x, _x.y, _x.radius, _x.area, _x.depth_m, _x.raw_depth_m, _x.diameter_depth_m, _x.calibrated_depth_m))
      _x = self.depth_source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2fB8f().pack(_x.center_offset_x, _x.center_offset_y, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.body_distance_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.detected, _x.x, _x.y, _x.radius, _x.area, _x.depth_m, _x.raw_depth_m, _x.diameter_depth_m, _x.calibrated_depth_m,) = _get_struct_B2i6f().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.depth_source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.depth_source = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.center_offset_x, _x.center_offset_y, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.body_x_m, _x.body_y_m, _x.body_z_m, _x.body_distance_m,) = _get_struct_2fB8f().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fB8f = None
def _get_struct_2fB8f():
    global _struct_2fB8f
    if _struct_2fB8f is None:
        _struct_2fB8f = struct.Struct("<2fB8f")
    return _struct_2fB8f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B2i6f = None
def _get_struct_B2i6f():
    global _struct_B2i6f
    if _struct_B2i6f is None:
        _struct_B2i6f = struct.Struct("<B2i6f")
    return _struct_B2i6f
