// Generated by gencpp from file d435i_yellow_circle_detector/GeoTarget.msg
// DO NOT EDIT!


#ifndef D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_GEOTARGET_H
#define D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_GEOTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace d435i_yellow_circle_detector
{
template <class ContainerAllocator>
struct GeoTarget_
{
  typedef GeoTarget_<ContainerAllocator> Type;

  GeoTarget_()
    : header()
    , valid(false)
    , status()
    , source_topic()
    , class_name()
    , confidence(0.0)
    , center_x(0)
    , center_y(0)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , body_x_m(0.0)
    , body_y_m(0.0)
    , body_z_m(0.0)
    , enu_east_m(0.0)
    , enu_north_m(0.0)
    , enu_up_m(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  GeoTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , status(_alloc)
    , source_topic(_alloc)
    , class_name(_alloc)
    , confidence(0.0)
    , center_x(0)
    , center_y(0)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , body_x_m(0.0)
    , body_y_m(0.0)
    , body_z_m(0.0)
    , enu_east_m(0.0)
    , enu_north_m(0.0)
    , enu_up_m(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_topic_type;
  _source_topic_type source_topic;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;

   typedef float _camera_x_m_type;
  _camera_x_m_type camera_x_m;

   typedef float _camera_y_m_type;
  _camera_y_m_type camera_y_m;

   typedef float _camera_z_m_type;
  _camera_z_m_type camera_z_m;

   typedef float _body_x_m_type;
  _body_x_m_type body_x_m;

   typedef float _body_y_m_type;
  _body_y_m_type body_y_m;

   typedef float _body_z_m_type;
  _body_z_m_type body_z_m;

   typedef float _enu_east_m_type;
  _enu_east_m_type enu_east_m;

   typedef float _enu_north_m_type;
  _enu_north_m_type enu_north_m;

   typedef float _enu_up_m_type;
  _enu_up_m_type enu_up_m;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> const> ConstPtr;

}; // struct GeoTarget_

typedef ::d435i_yellow_circle_detector::GeoTarget_<std::allocator<void> > GeoTarget;

typedef boost::shared_ptr< ::d435i_yellow_circle_detector::GeoTarget > GeoTargetPtr;
typedef boost::shared_ptr< ::d435i_yellow_circle_detector::GeoTarget const> GeoTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.status == rhs.status &&
    lhs.source_topic == rhs.source_topic &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.camera_x_m == rhs.camera_x_m &&
    lhs.camera_y_m == rhs.camera_y_m &&
    lhs.camera_z_m == rhs.camera_z_m &&
    lhs.body_x_m == rhs.body_x_m &&
    lhs.body_y_m == rhs.body_y_m &&
    lhs.body_z_m == rhs.body_z_m &&
    lhs.enu_east_m == rhs.enu_east_m &&
    lhs.enu_north_m == rhs.enu_north_m &&
    lhs.enu_up_m == rhs.enu_up_m &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace d435i_yellow_circle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97435bcc3e1e35e6ba97ca5a2f45aeba";
  }

  static const char* value(const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97435bcc3e1e35e6ULL;
  static const uint64_t static_value2 = 0xba97ca5a2f45aebaULL;
};

template<class ContainerAllocator>
struct DataType< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d435i_yellow_circle_detector/GeoTarget";
  }

  static const char* value(const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool valid\n"
"string status\n"
"string source_topic\n"
"string class_name\n"
"float32 confidence\n"
"int32 center_x\n"
"int32 center_y\n"
"float32 camera_x_m\n"
"float32 camera_y_m\n"
"float32 camera_z_m\n"
"float32 body_x_m\n"
"float32 body_y_m\n"
"float32 body_z_m\n"
"float32 enu_east_m\n"
"float32 enu_north_m\n"
"float32 enu_up_m\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.status);
      stream.next(m.source_topic);
      stream.next(m.class_name);
      stream.next(m.confidence);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.camera_x_m);
      stream.next(m.camera_y_m);
      stream.next(m.camera_z_m);
      stream.next(m.body_x_m);
      stream.next(m.body_y_m);
      stream.next(m.body_z_m);
      stream.next(m.enu_east_m);
      stream.next(m.enu_north_m);
      stream.next(m.enu_up_m);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeoTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::d435i_yellow_circle_detector::GeoTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "source_topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_topic);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
    s << indent << "camera_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_x_m);
    s << indent << "camera_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_y_m);
    s << indent << "camera_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_z_m);
    s << indent << "body_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_x_m);
    s << indent << "body_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_y_m);
    s << indent << "body_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_z_m);
    s << indent << "enu_east_m: ";
    Printer<float>::stream(s, indent + "  ", v.enu_east_m);
    s << indent << "enu_north_m: ";
    Printer<float>::stream(s, indent + "  ", v.enu_north_m);
    s << indent << "enu_up_m: ";
    Printer<float>::stream(s, indent + "  ", v.enu_up_m);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_GEOTARGET_H
