// Generated by gencpp from file d435i_yellow_circle_detector/YellowCircle.msg
// DO NOT EDIT!


#ifndef D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YELLOWCIRCLE_H
#define D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YELLOWCIRCLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace d435i_yellow_circle_detector
{
template <class ContainerAllocator>
struct YellowCircle_
{
  typedef YellowCircle_<ContainerAllocator> Type;

  YellowCircle_()
    : header()
    , detected(false)
    , x(0)
    , y(0)
    , radius(0.0)
    , area(0.0)
    , depth_m(0.0)
    , raw_depth_m(0.0)
    , diameter_depth_m(0.0)
    , calibrated_depth_m(0.0)
    , depth_source()
    , center_offset_x(0.0)
    , center_offset_y(0.0)
    , position_valid(false)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , body_x_m(0.0)
    , body_y_m(0.0)
    , body_z_m(0.0)
    , body_distance_m(0.0)  {
    }
  YellowCircle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected(false)
    , x(0)
    , y(0)
    , radius(0.0)
    , area(0.0)
    , depth_m(0.0)
    , raw_depth_m(0.0)
    , diameter_depth_m(0.0)
    , calibrated_depth_m(0.0)
    , depth_source(_alloc)
    , center_offset_x(0.0)
    , center_offset_y(0.0)
    , position_valid(false)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , body_x_m(0.0)
    , body_y_m(0.0)
    , body_z_m(0.0)
    , body_distance_m(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _area_type;
  _area_type area;

   typedef float _depth_m_type;
  _depth_m_type depth_m;

   typedef float _raw_depth_m_type;
  _raw_depth_m_type raw_depth_m;

   typedef float _diameter_depth_m_type;
  _diameter_depth_m_type diameter_depth_m;

   typedef float _calibrated_depth_m_type;
  _calibrated_depth_m_type calibrated_depth_m;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _depth_source_type;
  _depth_source_type depth_source;

   typedef float _center_offset_x_type;
  _center_offset_x_type center_offset_x;

   typedef float _center_offset_y_type;
  _center_offset_y_type center_offset_y;

   typedef uint8_t _position_valid_type;
  _position_valid_type position_valid;

   typedef float _camera_x_m_type;
  _camera_x_m_type camera_x_m;

   typedef float _camera_y_m_type;
  _camera_y_m_type camera_y_m;

   typedef float _camera_z_m_type;
  _camera_z_m_type camera_z_m;

   typedef float _distance_m_type;
  _distance_m_type distance_m;

   typedef float _body_x_m_type;
  _body_x_m_type body_x_m;

   typedef float _body_y_m_type;
  _body_y_m_type body_y_m;

   typedef float _body_z_m_type;
  _body_z_m_type body_z_m;

   typedef float _body_distance_m_type;
  _body_distance_m_type body_distance_m;





  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> const> ConstPtr;

}; // struct YellowCircle_

typedef ::d435i_yellow_circle_detector::YellowCircle_<std::allocator<void> > YellowCircle;

typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YellowCircle > YellowCirclePtr;
typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YellowCircle const> YellowCircleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected == rhs.detected &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.radius == rhs.radius &&
    lhs.area == rhs.area &&
    lhs.depth_m == rhs.depth_m &&
    lhs.raw_depth_m == rhs.raw_depth_m &&
    lhs.diameter_depth_m == rhs.diameter_depth_m &&
    lhs.calibrated_depth_m == rhs.calibrated_depth_m &&
    lhs.depth_source == rhs.depth_source &&
    lhs.center_offset_x == rhs.center_offset_x &&
    lhs.center_offset_y == rhs.center_offset_y &&
    lhs.position_valid == rhs.position_valid &&
    lhs.camera_x_m == rhs.camera_x_m &&
    lhs.camera_y_m == rhs.camera_y_m &&
    lhs.camera_z_m == rhs.camera_z_m &&
    lhs.distance_m == rhs.distance_m &&
    lhs.body_x_m == rhs.body_x_m &&
    lhs.body_y_m == rhs.body_y_m &&
    lhs.body_z_m == rhs.body_z_m &&
    lhs.body_distance_m == rhs.body_distance_m;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace d435i_yellow_circle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "546a21369cee59d7afb5df9576c1da21";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x546a21369cee59d7ULL;
  static const uint64_t static_value2 = 0xafb5df9576c1da21ULL;
};

template<class ContainerAllocator>
struct DataType< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d435i_yellow_circle_detector/YellowCircle";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool detected\n"
"int32 x\n"
"int32 y\n"
"float32 radius\n"
"float32 area\n"
"float32 depth_m\n"
"float32 raw_depth_m\n"
"float32 diameter_depth_m\n"
"float32 calibrated_depth_m\n"
"string depth_source\n"
"float32 center_offset_x\n"
"float32 center_offset_y\n"
"bool position_valid\n"
"float32 camera_x_m\n"
"float32 camera_y_m\n"
"float32 camera_z_m\n"
"float32 distance_m\n"
"float32 body_x_m\n"
"float32 body_y_m\n"
"float32 body_z_m\n"
"float32 body_distance_m\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
      stream.next(m.area);
      stream.next(m.depth_m);
      stream.next(m.raw_depth_m);
      stream.next(m.diameter_depth_m);
      stream.next(m.calibrated_depth_m);
      stream.next(m.depth_source);
      stream.next(m.center_offset_x);
      stream.next(m.center_offset_y);
      stream.next(m.position_valid);
      stream.next(m.camera_x_m);
      stream.next(m.camera_y_m);
      stream.next(m.camera_z_m);
      stream.next(m.distance_m);
      stream.next(m.body_x_m);
      stream.next(m.body_y_m);
      stream.next(m.body_z_m);
      stream.next(m.body_distance_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YellowCircle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::d435i_yellow_circle_detector::YellowCircle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
    s << indent << "depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.depth_m);
    s << indent << "raw_depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.raw_depth_m);
    s << indent << "diameter_depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.diameter_depth_m);
    s << indent << "calibrated_depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.calibrated_depth_m);
    s << indent << "depth_source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.depth_source);
    s << indent << "center_offset_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_offset_x);
    s << indent << "center_offset_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_offset_y);
    s << indent << "position_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_valid);
    s << indent << "camera_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_x_m);
    s << indent << "camera_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_y_m);
    s << indent << "camera_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_z_m);
    s << indent << "distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.distance_m);
    s << indent << "body_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_x_m);
    s << indent << "body_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_y_m);
    s << indent << "body_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_z_m);
    s << indent << "body_distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.body_distance_m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YELLOWCIRCLE_H
