// Generated by gencpp from file d435i_yellow_circle_detector/YoloDetections.msg
// DO NOT EDIT!


#ifndef D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTIONS_H
#define D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <d435i_yellow_circle_detector/YoloDetection.h>

namespace d435i_yellow_circle_detector
{
template <class ContainerAllocator>
struct YoloDetections_
{
  typedef YoloDetections_<ContainerAllocator> Type;

  YoloDetections_()
    : header()
    , detections()  {
    }
  YoloDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetections_

typedef ::d435i_yellow_circle_detector::YoloDetections_<std::allocator<void> > YoloDetections;

typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetections > YoloDetectionsPtr;
typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetections const> YoloDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace d435i_yellow_circle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a930238f1ca26e45c4d2a892c5bf7982";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa930238f1ca26e45ULL;
  static const uint64_t static_value2 = 0xc4d2a892c5bf7982ULL;
};

template<class ContainerAllocator>
struct DataType< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d435i_yellow_circle_detector/YoloDetections";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"YoloDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: d435i_yellow_circle_detector/YoloDetection\n"
"Header header\n"
"bool detected\n"
"int32 class_id\n"
"string class_name\n"
"float32 confidence\n"
"int32 x_min\n"
"int32 y_min\n"
"int32 x_max\n"
"int32 y_max\n"
"int32 center_x\n"
"int32 center_y\n"
"float32 depth_m\n"
"bool position_valid\n"
"float32 camera_x_m\n"
"float32 camera_y_m\n"
"float32 camera_z_m\n"
"float32 distance_m\n"
"float32 bbox_width_m\n"
"float32 bbox_height_m\n"
;
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::d435i_yellow_circle_detector::YoloDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTIONS_H
