# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cuadc_vision/BucketAimInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class BucketAimInfo(genpy.Message):
  _md5sum = "781270f5d3447ff4d4ce3194c04670ee"
  _type = "cuadc_vision/BucketAimInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Stable bucket center and physical A/B dropper aim points.
Header header
int32 count

# True when detection, depth, intrinsics, pixel aim points and metric deltas are valid.
# NED validity is reported independently because local_pose may be unavailable.
bool valid

int32 bucket_center_x
int32 bucket_center_y

int32 a_aim_x
int32 a_aim_y
int32 b_aim_x
int32 b_aim_y

# Delta convention: delta = aim_point - image_center.
# Pixel deltas use image axes (x right, y down).
float32 a_delta_x_px
float32 a_delta_y_px
float32 b_delta_x_px
float32 b_delta_y_px

# Metric deltas are estimated from the current target depth and camera intrinsics.
float32 a_delta_x_m
float32 a_delta_y_m
float32 b_delta_x_m
float32 b_delta_y_m

# Absolute target positions in the MAVROS local NED frame.
bool a_ned_valid
float32 a_ned_n
float32 a_ned_e
float32 a_ned_d

bool b_ned_valid
float32 b_ned_n
float32 b_ned_e
float32 b_ned_d

float32 confidence
string source_class

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','count','valid','bucket_center_x','bucket_center_y','a_aim_x','a_aim_y','b_aim_x','b_aim_y','a_delta_x_px','a_delta_y_px','b_delta_x_px','b_delta_y_px','a_delta_x_m','a_delta_y_m','b_delta_x_m','b_delta_y_m','a_ned_valid','a_ned_n','a_ned_e','a_ned_d','b_ned_valid','b_ned_n','b_ned_e','b_ned_d','confidence','source_class']
  _slot_types = ['std_msgs/Header','int32','bool','int32','int32','int32','int32','int32','int32','float32','float32','float32','float32','float32','float32','float32','float32','bool','float32','float32','float32','bool','float32','float32','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,count,valid,bucket_center_x,bucket_center_y,a_aim_x,a_aim_y,b_aim_x,b_aim_y,a_delta_x_px,a_delta_y_px,b_delta_x_px,b_delta_y_px,a_delta_x_m,a_delta_y_m,b_delta_x_m,b_delta_y_m,a_ned_valid,a_ned_n,a_ned_e,a_ned_d,b_ned_valid,b_ned_n,b_ned_e,b_ned_d,confidence,source_class

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BucketAimInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.count is None:
        self.count = 0
      if self.valid is None:
        self.valid = False
      if self.bucket_center_x is None:
        self.bucket_center_x = 0
      if self.bucket_center_y is None:
        self.bucket_center_y = 0
      if self.a_aim_x is None:
        self.a_aim_x = 0
      if self.a_aim_y is None:
        self.a_aim_y = 0
      if self.b_aim_x is None:
        self.b_aim_x = 0
      if self.b_aim_y is None:
        self.b_aim_y = 0
      if self.a_delta_x_px is None:
        self.a_delta_x_px = 0.
      if self.a_delta_y_px is None:
        self.a_delta_y_px = 0.
      if self.b_delta_x_px is None:
        self.b_delta_x_px = 0.
      if self.b_delta_y_px is None:
        self.b_delta_y_px = 0.
      if self.a_delta_x_m is None:
        self.a_delta_x_m = 0.
      if self.a_delta_y_m is None:
        self.a_delta_y_m = 0.
      if self.b_delta_x_m is None:
        self.b_delta_x_m = 0.
      if self.b_delta_y_m is None:
        self.b_delta_y_m = 0.
      if self.a_ned_valid is None:
        self.a_ned_valid = False
      if self.a_ned_n is None:
        self.a_ned_n = 0.
      if self.a_ned_e is None:
        self.a_ned_e = 0.
      if self.a_ned_d is None:
        self.a_ned_d = 0.
      if self.b_ned_valid is None:
        self.b_ned_valid = False
      if self.b_ned_n is None:
        self.b_ned_n = 0.
      if self.b_ned_e is None:
        self.b_ned_e = 0.
      if self.b_ned_d is None:
        self.b_ned_d = 0.
      if self.confidence is None:
        self.confidence = 0.
      if self.source_class is None:
        self.source_class = ''
    else:
      self.header = std_msgs.msg.Header()
      self.count = 0
      self.valid = False
      self.bucket_center_x = 0
      self.bucket_center_y = 0
      self.a_aim_x = 0
      self.a_aim_y = 0
      self.b_aim_x = 0
      self.b_aim_y = 0
      self.a_delta_x_px = 0.
      self.a_delta_y_px = 0.
      self.b_delta_x_px = 0.
      self.b_delta_y_px = 0.
      self.a_delta_x_m = 0.
      self.a_delta_y_m = 0.
      self.b_delta_x_m = 0.
      self.b_delta_y_m = 0.
      self.a_ned_valid = False
      self.a_ned_n = 0.
      self.a_ned_e = 0.
      self.a_ned_d = 0.
      self.b_ned_valid = False
      self.b_ned_n = 0.
      self.b_ned_e = 0.
      self.b_ned_d = 0.
      self.confidence = 0.
      self.source_class = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_iB6i8fB3fB4f().pack(_x.count, _x.valid, _x.bucket_center_x, _x.bucket_center_y, _x.a_aim_x, _x.a_aim_y, _x.b_aim_x, _x.b_aim_y, _x.a_delta_x_px, _x.a_delta_y_px, _x.b_delta_x_px, _x.b_delta_y_px, _x.a_delta_x_m, _x.a_delta_y_m, _x.b_delta_x_m, _x.b_delta_y_m, _x.a_ned_valid, _x.a_ned_n, _x.a_ned_e, _x.a_ned_d, _x.b_ned_valid, _x.b_ned_n, _x.b_ned_e, _x.b_ned_d, _x.confidence))
      _x = self.source_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 91
      (_x.count, _x.valid, _x.bucket_center_x, _x.bucket_center_y, _x.a_aim_x, _x.a_aim_y, _x.b_aim_x, _x.b_aim_y, _x.a_delta_x_px, _x.a_delta_y_px, _x.b_delta_x_px, _x.b_delta_y_px, _x.a_delta_x_m, _x.a_delta_y_m, _x.b_delta_x_m, _x.b_delta_y_m, _x.a_ned_valid, _x.a_ned_n, _x.a_ned_e, _x.a_ned_d, _x.b_ned_valid, _x.b_ned_n, _x.b_ned_e, _x.b_ned_d, _x.confidence,) = _get_struct_iB6i8fB3fB4f().unpack(str[start:end])
      self.valid = bool(self.valid)
      self.a_ned_valid = bool(self.a_ned_valid)
      self.b_ned_valid = bool(self.b_ned_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_class = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_iB6i8fB3fB4f().pack(_x.count, _x.valid, _x.bucket_center_x, _x.bucket_center_y, _x.a_aim_x, _x.a_aim_y, _x.b_aim_x, _x.b_aim_y, _x.a_delta_x_px, _x.a_delta_y_px, _x.b_delta_x_px, _x.b_delta_y_px, _x.a_delta_x_m, _x.a_delta_y_m, _x.b_delta_x_m, _x.b_delta_y_m, _x.a_ned_valid, _x.a_ned_n, _x.a_ned_e, _x.a_ned_d, _x.b_ned_valid, _x.b_ned_n, _x.b_ned_e, _x.b_ned_d, _x.confidence))
      _x = self.source_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 91
      (_x.count, _x.valid, _x.bucket_center_x, _x.bucket_center_y, _x.a_aim_x, _x.a_aim_y, _x.b_aim_x, _x.b_aim_y, _x.a_delta_x_px, _x.a_delta_y_px, _x.b_delta_x_px, _x.b_delta_y_px, _x.a_delta_x_m, _x.a_delta_y_m, _x.b_delta_x_m, _x.b_delta_y_m, _x.a_ned_valid, _x.a_ned_n, _x.a_ned_e, _x.a_ned_d, _x.b_ned_valid, _x.b_ned_n, _x.b_ned_e, _x.b_ned_d, _x.confidence,) = _get_struct_iB6i8fB3fB4f().unpack(str[start:end])
      self.valid = bool(self.valid)
      self.a_ned_valid = bool(self.a_ned_valid)
      self.b_ned_valid = bool(self.b_ned_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.source_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.source_class = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_iB6i8fB3fB4f = None
def _get_struct_iB6i8fB3fB4f():
    global _struct_iB6i8fB3fB4f
    if _struct_iB6i8fB3fB4f is None:
        _struct_iB6i8fB3fB4f = struct.Struct("<iB6i8fB3fB4f")
    return _struct_iB6i8fB3fB4f
