# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from d435i_yellow_circle_detector/YoloDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class YoloDetection(genpy.Message):
  _md5sum = "c97190c54505fa4fe0a0e57bb2112989"
  _type = "d435i_yellow_circle_detector/YoloDetection"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
bool detected
int32 class_id
string class_name
float32 confidence
int32 x_min
int32 y_min
int32 x_max
int32 y_max
int32 center_x
int32 center_y
float32 depth_m
bool position_valid
float32 camera_x_m
float32 camera_y_m
float32 camera_z_m
float32 distance_m
float32 bbox_width_m
float32 bbox_height_m

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','detected','class_id','class_name','confidence','x_min','y_min','x_max','y_max','center_x','center_y','depth_m','position_valid','camera_x_m','camera_y_m','camera_z_m','distance_m','bbox_width_m','bbox_height_m']
  _slot_types = ['std_msgs/Header','bool','int32','string','float32','int32','int32','int32','int32','int32','int32','float32','bool','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,detected,class_id,class_name,confidence,x_min,y_min,x_max,y_max,center_x,center_y,depth_m,position_valid,camera_x_m,camera_y_m,camera_z_m,distance_m,bbox_width_m,bbox_height_m

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YoloDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.detected is None:
        self.detected = False
      if self.class_id is None:
        self.class_id = 0
      if self.class_name is None:
        self.class_name = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.x_min is None:
        self.x_min = 0
      if self.y_min is None:
        self.y_min = 0
      if self.x_max is None:
        self.x_max = 0
      if self.y_max is None:
        self.y_max = 0
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.depth_m is None:
        self.depth_m = 0.
      if self.position_valid is None:
        self.position_valid = False
      if self.camera_x_m is None:
        self.camera_x_m = 0.
      if self.camera_y_m is None:
        self.camera_y_m = 0.
      if self.camera_z_m is None:
        self.camera_z_m = 0.
      if self.distance_m is None:
        self.distance_m = 0.
      if self.bbox_width_m is None:
        self.bbox_width_m = 0.
      if self.bbox_height_m is None:
        self.bbox_height_m = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.detected = False
      self.class_id = 0
      self.class_name = ''
      self.confidence = 0.
      self.x_min = 0
      self.y_min = 0
      self.x_max = 0
      self.y_max = 0
      self.center_x = 0
      self.center_y = 0
      self.depth_m = 0.
      self.position_valid = False
      self.camera_x_m = 0.
      self.camera_y_m = 0.
      self.camera_z_m = 0.
      self.distance_m = 0.
      self.bbox_width_m = 0.
      self.bbox_height_m = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.detected, _x.class_id))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6ifB6f().pack(_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.center_x, _x.center_y, _x.depth_m, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.detected, _x.class_id,) = _get_struct_Bi().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.center_x, _x.center_y, _x.depth_m, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m,) = _get_struct_f6ifB6f().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.detected, _x.class_id))
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f6ifB6f().pack(_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.center_x, _x.center_y, _x.depth_m, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.detected, _x.class_id,) = _get_struct_Bi().unpack(str[start:end])
      self.detected = bool(self.detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.center_x, _x.center_y, _x.depth_m, _x.position_valid, _x.camera_x_m, _x.camera_y_m, _x.camera_z_m, _x.distance_m, _x.bbox_width_m, _x.bbox_height_m,) = _get_struct_f6ifB6f().unpack(str[start:end])
      self.position_valid = bool(self.position_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bi = None
def _get_struct_Bi():
    global _struct_Bi
    if _struct_Bi is None:
        _struct_Bi = struct.Struct("<Bi")
    return _struct_Bi
_struct_f6ifB6f = None
def _get_struct_f6ifB6f():
    global _struct_f6ifB6f
    if _struct_f6ifB6f is None:
        _struct_f6ifB6f = struct.Struct("<f6ifB6f")
    return _struct_f6ifB6f
