set(_CATKIN_CURRENT_PACKAGE "cuadc_control")
set(cuadc_control_VERSION "1.0.0")
set(cuadc_control_MAINTAINER "CUADC Control Team <cuadc@example.com>")
set(cuadc_control_PACKAGE_FORMAT "2")
set(cuadc_control_BUILD_DEPENDS "rospy" "geometry_msgs" "mavros_msgs" "sensor_msgs" "std_msgs" "cuadc_vision")
set(cuadc_control_BUILD_EXPORT_DEPENDS )
set(cuadc_control_BUILDTOOL_DEPENDS "catkin")
set(cuadc_control_BUILDTOOL_EXPORT_DEPENDS )
set(cuadc_control_EXEC_DEPENDS "rospy" "roslaunch" "rosnode" "geometry_msgs" "mavros_msgs" "sensor_msgs" "std_msgs" "cuadc_vision")
set(cuadc_control_RUN_DEPENDS "rospy" "roslaunch" "rosnode" "geometry_msgs" "mavros_msgs" "sensor_msgs" "std_msgs" "cuadc_vision")
set(cuadc_control_TEST_DEPENDS )
set(cuadc_control_DOC_DEPENDS )
set(cuadc_control_URL_WEBSITE "")
set(cuadc_control_URL_BUGTRACKER "")
set(cuadc_control_URL_REPOSITORY "")
set(cuadc_control_DEPRECATED "")