// Generated by gencpp from file d435i_yellow_circle_detector/MissionTarget.msg
// DO NOT EDIT!


#ifndef D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_MISSIONTARGET_H
#define D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_MISSIONTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace d435i_yellow_circle_detector
{
template <class ContainerAllocator>
struct MissionTarget_
{
  typedef MissionTarget_<ContainerAllocator> Type;

  MissionTarget_()
    : header()
    , valid(false)
    , mission_stage()
    , target_type()
    , class_name()
    , confidence(0.0)
    , center_x(0)
    , center_y(0)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , bbox_width_m(0.0)
    , bbox_height_m(0.0)
    , nominal_diameter_m(0.0)
    , diameter_class()
    , zone_hint()
    , a_zone_radius_m(0.0)
    , b_zone_radius_m(0.0)
    , action_hint()  {
    }
  MissionTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , valid(false)
    , mission_stage(_alloc)
    , target_type(_alloc)
    , class_name(_alloc)
    , confidence(0.0)
    , center_x(0)
    , center_y(0)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , bbox_width_m(0.0)
    , bbox_height_m(0.0)
    , nominal_diameter_m(0.0)
    , diameter_class(_alloc)
    , zone_hint(_alloc)
    , a_zone_radius_m(0.0)
    , b_zone_radius_m(0.0)
    , action_hint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_stage_type;
  _mission_stage_type mission_stage;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type_type;
  _target_type_type target_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;

   typedef float _camera_x_m_type;
  _camera_x_m_type camera_x_m;

   typedef float _camera_y_m_type;
  _camera_y_m_type camera_y_m;

   typedef float _camera_z_m_type;
  _camera_z_m_type camera_z_m;

   typedef float _distance_m_type;
  _distance_m_type distance_m;

   typedef float _bbox_width_m_type;
  _bbox_width_m_type bbox_width_m;

   typedef float _bbox_height_m_type;
  _bbox_height_m_type bbox_height_m;

   typedef float _nominal_diameter_m_type;
  _nominal_diameter_m_type nominal_diameter_m;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _diameter_class_type;
  _diameter_class_type diameter_class;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _zone_hint_type;
  _zone_hint_type zone_hint;

   typedef float _a_zone_radius_m_type;
  _a_zone_radius_m_type a_zone_radius_m;

   typedef float _b_zone_radius_m_type;
  _b_zone_radius_m_type b_zone_radius_m;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_hint_type;
  _action_hint_type action_hint;





  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> const> ConstPtr;

}; // struct MissionTarget_

typedef ::d435i_yellow_circle_detector::MissionTarget_<std::allocator<void> > MissionTarget;

typedef boost::shared_ptr< ::d435i_yellow_circle_detector::MissionTarget > MissionTargetPtr;
typedef boost::shared_ptr< ::d435i_yellow_circle_detector::MissionTarget const> MissionTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.valid == rhs.valid &&
    lhs.mission_stage == rhs.mission_stage &&
    lhs.target_type == rhs.target_type &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.camera_x_m == rhs.camera_x_m &&
    lhs.camera_y_m == rhs.camera_y_m &&
    lhs.camera_z_m == rhs.camera_z_m &&
    lhs.distance_m == rhs.distance_m &&
    lhs.bbox_width_m == rhs.bbox_width_m &&
    lhs.bbox_height_m == rhs.bbox_height_m &&
    lhs.nominal_diameter_m == rhs.nominal_diameter_m &&
    lhs.diameter_class == rhs.diameter_class &&
    lhs.zone_hint == rhs.zone_hint &&
    lhs.a_zone_radius_m == rhs.a_zone_radius_m &&
    lhs.b_zone_radius_m == rhs.b_zone_radius_m &&
    lhs.action_hint == rhs.action_hint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace d435i_yellow_circle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e275971ddc71593e97b9bdc197f8cad";
  }

  static const char* value(const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e275971ddc71593ULL;
  static const uint64_t static_value2 = 0xe97b9bdc197f8cadULL;
};

template<class ContainerAllocator>
struct DataType< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d435i_yellow_circle_detector/MissionTarget";
  }

  static const char* value(const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool valid\n"
"string mission_stage\n"
"string target_type\n"
"string class_name\n"
"float32 confidence\n"
"int32 center_x\n"
"int32 center_y\n"
"float32 camera_x_m\n"
"float32 camera_y_m\n"
"float32 camera_z_m\n"
"float32 distance_m\n"
"float32 bbox_width_m\n"
"float32 bbox_height_m\n"
"float32 nominal_diameter_m\n"
"string diameter_class\n"
"string zone_hint\n"
"float32 a_zone_radius_m\n"
"float32 b_zone_radius_m\n"
"string action_hint\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.valid);
      stream.next(m.mission_stage);
      stream.next(m.target_type);
      stream.next(m.class_name);
      stream.next(m.confidence);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.camera_x_m);
      stream.next(m.camera_y_m);
      stream.next(m.camera_z_m);
      stream.next(m.distance_m);
      stream.next(m.bbox_width_m);
      stream.next(m.bbox_height_m);
      stream.next(m.nominal_diameter_m);
      stream.next(m.diameter_class);
      stream.next(m.zone_hint);
      stream.next(m.a_zone_radius_m);
      stream.next(m.b_zone_radius_m);
      stream.next(m.action_hint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::d435i_yellow_circle_detector::MissionTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "mission_stage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission_stage);
    s << indent << "target_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target_type);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
    s << indent << "camera_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_x_m);
    s << indent << "camera_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_y_m);
    s << indent << "camera_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_z_m);
    s << indent << "distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.distance_m);
    s << indent << "bbox_width_m: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_width_m);
    s << indent << "bbox_height_m: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_height_m);
    s << indent << "nominal_diameter_m: ";
    Printer<float>::stream(s, indent + "  ", v.nominal_diameter_m);
    s << indent << "diameter_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.diameter_class);
    s << indent << "zone_hint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.zone_hint);
    s << indent << "a_zone_radius_m: ";
    Printer<float>::stream(s, indent + "  ", v.a_zone_radius_m);
    s << indent << "b_zone_radius_m: ";
    Printer<float>::stream(s, indent + "  ", v.b_zone_radius_m);
    s << indent << "action_hint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action_hint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_MISSIONTARGET_H
