// Generated by gencpp from file d435i_yellow_circle_detector/YoloDetection.msg
// DO NOT EDIT!


#ifndef D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTION_H
#define D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace d435i_yellow_circle_detector
{
template <class ContainerAllocator>
struct YoloDetection_
{
  typedef YoloDetection_<ContainerAllocator> Type;

  YoloDetection_()
    : header()
    , detected(false)
    , class_id(0)
    , class_name()
    , confidence(0.0)
    , x_min(0)
    , y_min(0)
    , x_max(0)
    , y_max(0)
    , center_x(0)
    , center_y(0)
    , depth_m(0.0)
    , position_valid(false)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , bbox_width_m(0.0)
    , bbox_height_m(0.0)  {
    }
  YoloDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected(false)
    , class_id(0)
    , class_name(_alloc)
    , confidence(0.0)
    , x_min(0)
    , y_min(0)
    , x_max(0)
    , y_max(0)
    , center_x(0)
    , center_y(0)
    , depth_m(0.0)
    , position_valid(false)
    , camera_x_m(0.0)
    , camera_y_m(0.0)
    , camera_z_m(0.0)
    , distance_m(0.0)
    , bbox_width_m(0.0)
    , bbox_height_m(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _x_min_type;
  _x_min_type x_min;

   typedef int32_t _y_min_type;
  _y_min_type y_min;

   typedef int32_t _x_max_type;
  _x_max_type x_max;

   typedef int32_t _y_max_type;
  _y_max_type y_max;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;

   typedef float _depth_m_type;
  _depth_m_type depth_m;

   typedef uint8_t _position_valid_type;
  _position_valid_type position_valid;

   typedef float _camera_x_m_type;
  _camera_x_m_type camera_x_m;

   typedef float _camera_y_m_type;
  _camera_y_m_type camera_y_m;

   typedef float _camera_z_m_type;
  _camera_z_m_type camera_z_m;

   typedef float _distance_m_type;
  _distance_m_type distance_m;

   typedef float _bbox_width_m_type;
  _bbox_width_m_type bbox_width_m;

   typedef float _bbox_height_m_type;
  _bbox_height_m_type bbox_height_m;





  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetection_

typedef ::d435i_yellow_circle_detector::YoloDetection_<std::allocator<void> > YoloDetection;

typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetection > YoloDetectionPtr;
typedef boost::shared_ptr< ::d435i_yellow_circle_detector::YoloDetection const> YoloDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detected == rhs.detected &&
    lhs.class_id == rhs.class_id &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence &&
    lhs.x_min == rhs.x_min &&
    lhs.y_min == rhs.y_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_max == rhs.y_max &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.depth_m == rhs.depth_m &&
    lhs.position_valid == rhs.position_valid &&
    lhs.camera_x_m == rhs.camera_x_m &&
    lhs.camera_y_m == rhs.camera_y_m &&
    lhs.camera_z_m == rhs.camera_z_m &&
    lhs.distance_m == rhs.distance_m &&
    lhs.bbox_width_m == rhs.bbox_width_m &&
    lhs.bbox_height_m == rhs.bbox_height_m;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator1> & lhs, const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace d435i_yellow_circle_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c97190c54505fa4fe0a0e57bb2112989";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc97190c54505fa4fULL;
  static const uint64_t static_value2 = 0xe0a0e57bb2112989ULL;
};

template<class ContainerAllocator>
struct DataType< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d435i_yellow_circle_detector/YoloDetection";
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool detected\n"
"int32 class_id\n"
"string class_name\n"
"float32 confidence\n"
"int32 x_min\n"
"int32 y_min\n"
"int32 x_max\n"
"int32 y_max\n"
"int32 center_x\n"
"int32 center_y\n"
"float32 depth_m\n"
"bool position_valid\n"
"float32 camera_x_m\n"
"float32 camera_y_m\n"
"float32 camera_z_m\n"
"float32 distance_m\n"
"float32 bbox_width_m\n"
"float32 bbox_height_m\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected);
      stream.next(m.class_id);
      stream.next(m.class_name);
      stream.next(m.confidence);
      stream.next(m.x_min);
      stream.next(m.y_min);
      stream.next(m.x_max);
      stream.next(m.y_max);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.depth_m);
      stream.next(m.position_valid);
      stream.next(m.camera_x_m);
      stream.next(m.camera_y_m);
      stream.next(m.camera_z_m);
      stream.next(m.distance_m);
      stream.next(m.bbox_width_m);
      stream.next(m.bbox_height_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::d435i_yellow_circle_detector::YoloDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "x_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_min);
    s << indent << "y_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_min);
    s << indent << "x_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_max);
    s << indent << "y_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_max);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
    s << indent << "depth_m: ";
    Printer<float>::stream(s, indent + "  ", v.depth_m);
    s << indent << "position_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_valid);
    s << indent << "camera_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_x_m);
    s << indent << "camera_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_y_m);
    s << indent << "camera_z_m: ";
    Printer<float>::stream(s, indent + "  ", v.camera_z_m);
    s << indent << "distance_m: ";
    Printer<float>::stream(s, indent + "  ", v.distance_m);
    s << indent << "bbox_width_m: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_width_m);
    s << indent << "bbox_height_m: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_height_m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // D435I_YELLOW_CIRCLE_DETECTOR_MESSAGE_YOLODETECTION_H
