(cl:in-package cuadc_vision-msg)
(cl:export '(HEADER-VAL
          HEADER
          DETECTED-VAL
          DETECTED
          CLASS_ID-VAL
          CLASS_ID
          CLASS_NAME-VAL
          CLASS_NAME
          CONFIDENCE-VAL
          CONFIDENCE
          X_MIN-VAL
          X_MIN
          Y_MIN-VAL
          Y_MIN
          X_MAX-VAL
          X_MAX
          Y_MAX-VAL
          Y_MAX
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          DEPTH_M-VAL
          DEPTH_M
          POSITION_VALID-VAL
          POSITION_VALID
          CAMERA_X_M-VAL
          CAMERA_X_M
          CAMERA_Y_M-VAL
          CAMERA_Y_M
          CAMERA_Z_M-VAL
          CAMERA_Z_M
          DISTANCE_M-VAL
          DISTANCE_M
          BBOX_WIDTH_M-VAL
          BBOX_WIDTH_M
          BBOX_HEIGHT_M-VAL
          BBOX_HEIGHT_M
))