// Generated by gencpp from file cuadc_vision/BucketAimInfo.msg
// DO NOT EDIT!


#ifndef CUADC_VISION_MESSAGE_BUCKETAIMINFO_H
#define CUADC_VISION_MESSAGE_BUCKETAIMINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cuadc_vision
{
template <class ContainerAllocator>
struct BucketAimInfo_
{
  typedef BucketAimInfo_<ContainerAllocator> Type;

  BucketAimInfo_()
    : header()
    , count(0)
    , valid(false)
    , bucket_center_x(0)
    , bucket_center_y(0)
    , a_aim_x(0)
    , a_aim_y(0)
    , b_aim_x(0)
    , b_aim_y(0)
    , a_delta_x_px(0.0)
    , a_delta_y_px(0.0)
    , b_delta_x_px(0.0)
    , b_delta_y_px(0.0)
    , a_delta_x_m(0.0)
    , a_delta_y_m(0.0)
    , b_delta_x_m(0.0)
    , b_delta_y_m(0.0)
    , a_ned_valid(false)
    , a_ned_n(0.0)
    , a_ned_e(0.0)
    , a_ned_d(0.0)
    , b_ned_valid(false)
    , b_ned_n(0.0)
    , b_ned_e(0.0)
    , b_ned_d(0.0)
    , confidence(0.0)
    , source_class()  {
    }
  BucketAimInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , valid(false)
    , bucket_center_x(0)
    , bucket_center_y(0)
    , a_aim_x(0)
    , a_aim_y(0)
    , b_aim_x(0)
    , b_aim_y(0)
    , a_delta_x_px(0.0)
    , a_delta_y_px(0.0)
    , b_delta_x_px(0.0)
    , b_delta_y_px(0.0)
    , a_delta_x_m(0.0)
    , a_delta_y_m(0.0)
    , b_delta_x_m(0.0)
    , b_delta_y_m(0.0)
    , a_ned_valid(false)
    , a_ned_n(0.0)
    , a_ned_e(0.0)
    , a_ned_d(0.0)
    , b_ned_valid(false)
    , b_ned_n(0.0)
    , b_ned_e(0.0)
    , b_ned_d(0.0)
    , confidence(0.0)
    , source_class(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _count_type;
  _count_type count;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef int32_t _bucket_center_x_type;
  _bucket_center_x_type bucket_center_x;

   typedef int32_t _bucket_center_y_type;
  _bucket_center_y_type bucket_center_y;

   typedef int32_t _a_aim_x_type;
  _a_aim_x_type a_aim_x;

   typedef int32_t _a_aim_y_type;
  _a_aim_y_type a_aim_y;

   typedef int32_t _b_aim_x_type;
  _b_aim_x_type b_aim_x;

   typedef int32_t _b_aim_y_type;
  _b_aim_y_type b_aim_y;

   typedef float _a_delta_x_px_type;
  _a_delta_x_px_type a_delta_x_px;

   typedef float _a_delta_y_px_type;
  _a_delta_y_px_type a_delta_y_px;

   typedef float _b_delta_x_px_type;
  _b_delta_x_px_type b_delta_x_px;

   typedef float _b_delta_y_px_type;
  _b_delta_y_px_type b_delta_y_px;

   typedef float _a_delta_x_m_type;
  _a_delta_x_m_type a_delta_x_m;

   typedef float _a_delta_y_m_type;
  _a_delta_y_m_type a_delta_y_m;

   typedef float _b_delta_x_m_type;
  _b_delta_x_m_type b_delta_x_m;

   typedef float _b_delta_y_m_type;
  _b_delta_y_m_type b_delta_y_m;

   typedef uint8_t _a_ned_valid_type;
  _a_ned_valid_type a_ned_valid;

   typedef float _a_ned_n_type;
  _a_ned_n_type a_ned_n;

   typedef float _a_ned_e_type;
  _a_ned_e_type a_ned_e;

   typedef float _a_ned_d_type;
  _a_ned_d_type a_ned_d;

   typedef uint8_t _b_ned_valid_type;
  _b_ned_valid_type b_ned_valid;

   typedef float _b_ned_n_type;
  _b_ned_n_type b_ned_n;

   typedef float _b_ned_e_type;
  _b_ned_e_type b_ned_e;

   typedef float _b_ned_d_type;
  _b_ned_d_type b_ned_d;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_class_type;
  _source_class_type source_class;





  typedef boost::shared_ptr< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BucketAimInfo_

typedef ::cuadc_vision::BucketAimInfo_<std::allocator<void> > BucketAimInfo;

typedef boost::shared_ptr< ::cuadc_vision::BucketAimInfo > BucketAimInfoPtr;
typedef boost::shared_ptr< ::cuadc_vision::BucketAimInfo const> BucketAimInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cuadc_vision::BucketAimInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cuadc_vision::BucketAimInfo_<ContainerAllocator1> & lhs, const ::cuadc_vision::BucketAimInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.count == rhs.count &&
    lhs.valid == rhs.valid &&
    lhs.bucket_center_x == rhs.bucket_center_x &&
    lhs.bucket_center_y == rhs.bucket_center_y &&
    lhs.a_aim_x == rhs.a_aim_x &&
    lhs.a_aim_y == rhs.a_aim_y &&
    lhs.b_aim_x == rhs.b_aim_x &&
    lhs.b_aim_y == rhs.b_aim_y &&
    lhs.a_delta_x_px == rhs.a_delta_x_px &&
    lhs.a_delta_y_px == rhs.a_delta_y_px &&
    lhs.b_delta_x_px == rhs.b_delta_x_px &&
    lhs.b_delta_y_px == rhs.b_delta_y_px &&
    lhs.a_delta_x_m == rhs.a_delta_x_m &&
    lhs.a_delta_y_m == rhs.a_delta_y_m &&
    lhs.b_delta_x_m == rhs.b_delta_x_m &&
    lhs.b_delta_y_m == rhs.b_delta_y_m &&
    lhs.a_ned_valid == rhs.a_ned_valid &&
    lhs.a_ned_n == rhs.a_ned_n &&
    lhs.a_ned_e == rhs.a_ned_e &&
    lhs.a_ned_d == rhs.a_ned_d &&
    lhs.b_ned_valid == rhs.b_ned_valid &&
    lhs.b_ned_n == rhs.b_ned_n &&
    lhs.b_ned_e == rhs.b_ned_e &&
    lhs.b_ned_d == rhs.b_ned_d &&
    lhs.confidence == rhs.confidence &&
    lhs.source_class == rhs.source_class;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cuadc_vision::BucketAimInfo_<ContainerAllocator1> & lhs, const ::cuadc_vision::BucketAimInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cuadc_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "781270f5d3447ff4d4ce3194c04670ee";
  }

  static const char* value(const ::cuadc_vision::BucketAimInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x781270f5d3447ff4ULL;
  static const uint64_t static_value2 = 0xd4ce3194c04670eeULL;
};

template<class ContainerAllocator>
struct DataType< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cuadc_vision/BucketAimInfo";
  }

  static const char* value(const ::cuadc_vision::BucketAimInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Stable bucket center and physical A/B dropper aim points.\n"
"Header header\n"
"int32 count\n"
"\n"
"# True when detection, depth, intrinsics, pixel aim points and metric deltas are valid.\n"
"# NED validity is reported independently because local_pose may be unavailable.\n"
"bool valid\n"
"\n"
"int32 bucket_center_x\n"
"int32 bucket_center_y\n"
"\n"
"int32 a_aim_x\n"
"int32 a_aim_y\n"
"int32 b_aim_x\n"
"int32 b_aim_y\n"
"\n"
"# Delta convention: delta = aim_point - image_center.\n"
"# Pixel deltas use image axes (x right, y down).\n"
"float32 a_delta_x_px\n"
"float32 a_delta_y_px\n"
"float32 b_delta_x_px\n"
"float32 b_delta_y_px\n"
"\n"
"# Metric deltas are estimated from the current target depth and camera intrinsics.\n"
"float32 a_delta_x_m\n"
"float32 a_delta_y_m\n"
"float32 b_delta_x_m\n"
"float32 b_delta_y_m\n"
"\n"
"# Absolute target positions in the MAVROS local NED frame.\n"
"bool a_ned_valid\n"
"float32 a_ned_n\n"
"float32 a_ned_e\n"
"float32 a_ned_d\n"
"\n"
"bool b_ned_valid\n"
"float32 b_ned_n\n"
"float32 b_ned_e\n"
"float32 b_ned_d\n"
"\n"
"float32 confidence\n"
"string source_class\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cuadc_vision::BucketAimInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.valid);
      stream.next(m.bucket_center_x);
      stream.next(m.bucket_center_y);
      stream.next(m.a_aim_x);
      stream.next(m.a_aim_y);
      stream.next(m.b_aim_x);
      stream.next(m.b_aim_y);
      stream.next(m.a_delta_x_px);
      stream.next(m.a_delta_y_px);
      stream.next(m.b_delta_x_px);
      stream.next(m.b_delta_y_px);
      stream.next(m.a_delta_x_m);
      stream.next(m.a_delta_y_m);
      stream.next(m.b_delta_x_m);
      stream.next(m.b_delta_y_m);
      stream.next(m.a_ned_valid);
      stream.next(m.a_ned_n);
      stream.next(m.a_ned_e);
      stream.next(m.a_ned_d);
      stream.next(m.b_ned_valid);
      stream.next(m.b_ned_n);
      stream.next(m.b_ned_e);
      stream.next(m.b_ned_d);
      stream.next(m.confidence);
      stream.next(m.source_class);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BucketAimInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cuadc_vision::BucketAimInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cuadc_vision::BucketAimInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "bucket_center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bucket_center_x);
    s << indent << "bucket_center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bucket_center_y);
    s << indent << "a_aim_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a_aim_x);
    s << indent << "a_aim_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a_aim_y);
    s << indent << "b_aim_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b_aim_x);
    s << indent << "b_aim_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b_aim_y);
    s << indent << "a_delta_x_px: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_x_px);
    s << indent << "a_delta_y_px: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_y_px);
    s << indent << "b_delta_x_px: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_x_px);
    s << indent << "b_delta_y_px: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_y_px);
    s << indent << "a_delta_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_x_m);
    s << indent << "a_delta_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_y_m);
    s << indent << "b_delta_x_m: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_x_m);
    s << indent << "b_delta_y_m: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_y_m);
    s << indent << "a_ned_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a_ned_valid);
    s << indent << "a_ned_n: ";
    Printer<float>::stream(s, indent + "  ", v.a_ned_n);
    s << indent << "a_ned_e: ";
    Printer<float>::stream(s, indent + "  ", v.a_ned_e);
    s << indent << "a_ned_d: ";
    Printer<float>::stream(s, indent + "  ", v.a_ned_d);
    s << indent << "b_ned_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b_ned_valid);
    s << indent << "b_ned_n: ";
    Printer<float>::stream(s, indent + "  ", v.b_ned_n);
    s << indent << "b_ned_e: ";
    Printer<float>::stream(s, indent + "  ", v.b_ned_e);
    s << indent << "b_ned_d: ";
    Printer<float>::stream(s, indent + "  ", v.b_ned_d);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "source_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_class);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUADC_VISION_MESSAGE_BUCKETAIMINFO_H
