// Generated by gencpp from file cuadc_vision/BucketInfo.msg
// DO NOT EDIT!


#ifndef CUADC_VISION_MESSAGE_BUCKETINFO_H
#define CUADC_VISION_MESSAGE_BUCKETINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cuadc_vision
{
template <class ContainerAllocator>
struct BucketInfo_
{
  typedef BucketInfo_<ContainerAllocator> Type;

  BucketInfo_()
    : header()
    , count(0)
    , delta_x(0.0)
    , delta_y(0.0)
    , aim_offsets_valid(false)
    , a_crosshair_x(0.0)
    , a_crosshair_y(0.0)
    , a_delta_x(0.0)
    , a_delta_y(0.0)
    , b_crosshair_x(0.0)
    , b_crosshair_y(0.0)
    , b_delta_x(0.0)
    , b_delta_y(0.0)  {
    }
  BucketInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , delta_x(0.0)
    , delta_y(0.0)
    , aim_offsets_valid(false)
    , a_crosshair_x(0.0)
    , a_crosshair_y(0.0)
    , a_delta_x(0.0)
    , a_delta_y(0.0)
    , b_crosshair_x(0.0)
    , b_crosshair_y(0.0)
    , b_delta_x(0.0)
    , b_delta_y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _count_type;
  _count_type count;

   typedef float _delta_x_type;
  _delta_x_type delta_x;

   typedef float _delta_y_type;
  _delta_y_type delta_y;

   typedef uint8_t _aim_offsets_valid_type;
  _aim_offsets_valid_type aim_offsets_valid;

   typedef float _a_crosshair_x_type;
  _a_crosshair_x_type a_crosshair_x;

   typedef float _a_crosshair_y_type;
  _a_crosshair_y_type a_crosshair_y;

   typedef float _a_delta_x_type;
  _a_delta_x_type a_delta_x;

   typedef float _a_delta_y_type;
  _a_delta_y_type a_delta_y;

   typedef float _b_crosshair_x_type;
  _b_crosshair_x_type b_crosshair_x;

   typedef float _b_crosshair_y_type;
  _b_crosshair_y_type b_crosshair_y;

   typedef float _b_delta_x_type;
  _b_delta_x_type b_delta_x;

   typedef float _b_delta_y_type;
  _b_delta_y_type b_delta_y;





  typedef boost::shared_ptr< ::cuadc_vision::BucketInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cuadc_vision::BucketInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BucketInfo_

typedef ::cuadc_vision::BucketInfo_<std::allocator<void> > BucketInfo;

typedef boost::shared_ptr< ::cuadc_vision::BucketInfo > BucketInfoPtr;
typedef boost::shared_ptr< ::cuadc_vision::BucketInfo const> BucketInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cuadc_vision::BucketInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cuadc_vision::BucketInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cuadc_vision::BucketInfo_<ContainerAllocator1> & lhs, const ::cuadc_vision::BucketInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.count == rhs.count &&
    lhs.delta_x == rhs.delta_x &&
    lhs.delta_y == rhs.delta_y &&
    lhs.aim_offsets_valid == rhs.aim_offsets_valid &&
    lhs.a_crosshair_x == rhs.a_crosshair_x &&
    lhs.a_crosshair_y == rhs.a_crosshair_y &&
    lhs.a_delta_x == rhs.a_delta_x &&
    lhs.a_delta_y == rhs.a_delta_y &&
    lhs.b_crosshair_x == rhs.b_crosshair_x &&
    lhs.b_crosshair_y == rhs.b_crosshair_y &&
    lhs.b_delta_x == rhs.b_delta_x &&
    lhs.b_delta_y == rhs.b_delta_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cuadc_vision::BucketInfo_<ContainerAllocator1> & lhs, const ::cuadc_vision::BucketInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cuadc_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::BucketInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::BucketInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::BucketInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bed88d5fcfa32d568a9fb5d9f22c5d7b";
  }

  static const char* value(const ::cuadc_vision::BucketInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbed88d5fcfa32d56ULL;
  static const uint64_t static_value2 = 0x8a9fb5d9f22c5d7bULL;
};

template<class ContainerAllocator>
struct DataType< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cuadc_vision/BucketInfo";
  }

  static const char* value(const ::cuadc_vision::BucketInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 count\n"
"float32 delta_x\n"
"float32 delta_y\n"
"bool aim_offsets_valid\n"
"float32 a_crosshair_x\n"
"float32 a_crosshair_y\n"
"float32 a_delta_x\n"
"float32 a_delta_y\n"
"float32 b_crosshair_x\n"
"float32 b_crosshair_y\n"
"float32 b_delta_x\n"
"float32 b_delta_y\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cuadc_vision::BucketInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.delta_x);
      stream.next(m.delta_y);
      stream.next(m.aim_offsets_valid);
      stream.next(m.a_crosshair_x);
      stream.next(m.a_crosshair_y);
      stream.next(m.a_delta_x);
      stream.next(m.a_delta_y);
      stream.next(m.b_crosshair_x);
      stream.next(m.b_crosshair_y);
      stream.next(m.b_delta_x);
      stream.next(m.b_delta_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BucketInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cuadc_vision::BucketInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cuadc_vision::BucketInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "delta_x: ";
    Printer<float>::stream(s, indent + "  ", v.delta_x);
    s << indent << "delta_y: ";
    Printer<float>::stream(s, indent + "  ", v.delta_y);
    s << indent << "aim_offsets_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aim_offsets_valid);
    s << indent << "a_crosshair_x: ";
    Printer<float>::stream(s, indent + "  ", v.a_crosshair_x);
    s << indent << "a_crosshair_y: ";
    Printer<float>::stream(s, indent + "  ", v.a_crosshair_y);
    s << indent << "a_delta_x: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_x);
    s << indent << "a_delta_y: ";
    Printer<float>::stream(s, indent + "  ", v.a_delta_y);
    s << indent << "b_crosshair_x: ";
    Printer<float>::stream(s, indent + "  ", v.b_crosshair_x);
    s << indent << "b_crosshair_y: ";
    Printer<float>::stream(s, indent + "  ", v.b_crosshair_y);
    s << indent << "b_delta_x: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_x);
    s << indent << "b_delta_y: ";
    Printer<float>::stream(s, indent + "  ", v.b_delta_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUADC_VISION_MESSAGE_BUCKETINFO_H
