// Generated by gencpp from file cuadc_vision/MissionStatus.msg
// DO NOT EDIT!


#ifndef CUADC_VISION_MESSAGE_MISSIONSTATUS_H
#define CUADC_VISION_MESSAGE_MISSIONSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cuadc_vision
{
template <class ContainerAllocator>
struct MissionStatus_
{
  typedef MissionStatus_<ContainerAllocator> Type;

  MissionStatus_()
    : ammo_a(0)
    , ammo_b(0)
    , aiming(false)
    , last_drop()  {
    }
  MissionStatus_(const ContainerAllocator& _alloc)
    : ammo_a(0)
    , ammo_b(0)
    , aiming(false)
    , last_drop(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ammo_a_type;
  _ammo_a_type ammo_a;

   typedef uint8_t _ammo_b_type;
  _ammo_b_type ammo_b;

   typedef uint8_t _aiming_type;
  _aiming_type aiming;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_drop_type;
  _last_drop_type last_drop;





  typedef boost::shared_ptr< ::cuadc_vision::MissionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cuadc_vision::MissionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatus_

typedef ::cuadc_vision::MissionStatus_<std::allocator<void> > MissionStatus;

typedef boost::shared_ptr< ::cuadc_vision::MissionStatus > MissionStatusPtr;
typedef boost::shared_ptr< ::cuadc_vision::MissionStatus const> MissionStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cuadc_vision::MissionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cuadc_vision::MissionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cuadc_vision::MissionStatus_<ContainerAllocator1> & lhs, const ::cuadc_vision::MissionStatus_<ContainerAllocator2> & rhs)
{
  return lhs.ammo_a == rhs.ammo_a &&
    lhs.ammo_b == rhs.ammo_b &&
    lhs.aiming == rhs.aiming &&
    lhs.last_drop == rhs.last_drop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cuadc_vision::MissionStatus_<ContainerAllocator1> & lhs, const ::cuadc_vision::MissionStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cuadc_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cuadc_vision::MissionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuadc_vision::MissionStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuadc_vision::MissionStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42a0745a697dd6adddaac7f2c09f5f59";
  }

  static const char* value(const ::cuadc_vision::MissionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42a0745a697dd6adULL;
  static const uint64_t static_value2 = 0xddaac7f2c09f5f59ULL;
};

template<class ContainerAllocator>
struct DataType< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cuadc_vision/MissionStatus";
  }

  static const char* value(const ::cuadc_vision::MissionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# MissionStatus.msg — main.py → detector_node 任务状态同步\n"
"#\n"
"# 用于 detector_node 在画面上显示弹药、瞄准、抛投等任务状态信息。\n"
"\n"
"uint8 ammo_a                # 前抛投器 (A) 剩余弹药数，0 表示无/未挂载\n"
"uint8 ammo_b                # 后抛投器 (B) 剩余弹药数，0 表示无/未挂载\n"
"bool aiming                 # 飞控处于 GUIDED 模式且正在执行对准任务\n"
"string last_drop            # 最近一次抛投的抛投器编号 (\"A\" / \"B\" / \"\")\n"
;
  }

  static const char* value(const ::cuadc_vision::MissionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ammo_a);
      stream.next(m.ammo_b);
      stream.next(m.aiming);
      stream.next(m.last_drop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cuadc_vision::MissionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cuadc_vision::MissionStatus_<ContainerAllocator>& v)
  {
    s << indent << "ammo_a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ammo_a);
    s << indent << "ammo_b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ammo_b);
    s << indent << "aiming: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aiming);
    s << indent << "last_drop: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_drop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUADC_VISION_MESSAGE_MISSIONSTATUS_H
