(cl:in-package d435i_yellow_circle_detector-msg)
(cl:export '(HEADER-VAL
          HEADER
          VALID-VAL
          VALID
          MISSION_STAGE-VAL
          MISSION_STAGE
          TARGET_TYPE-VAL
          TARGET_TYPE
          CLASS_NAME-VAL
          CLASS_NAME
          CONFIDENCE-VAL
          CONFIDENCE
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          CAMERA_X_M-VAL
          CAMERA_X_M
          CAMERA_Y_M-VAL
          CAMERA_Y_M
          CAMERA_Z_M-VAL
          CAMERA_Z_M
          DISTANCE_M-VAL
          DISTANCE_M
          BBOX_WIDTH_M-VAL
          BBOX_WIDTH_M
          BBOX_HEIGHT_M-VAL
          BBOX_HEIGHT_M
          NOMINAL_DIAMETER_M-VAL
          NOMINAL_DIAMETER_M
          DIAMETER_CLASS-VAL
          DIAMETER_CLASS
          ZONE_HINT-VAL
          ZONE_HINT
          A_ZONE_RADIUS_M-VAL
          A_ZONE_RADIUS_M
          B_ZONE_RADIUS_M-VAL
          B_ZONE_RADIUS_M
          ACTION_HINT-VAL
          ACTION_HINT
))