(cl:in-package d435i_yellow_circle_detector-msg)
(cl:export '(HEADER-VAL
          HEADER
          DETECTED-VAL
          DETECTED
          X-VAL
          X
          Y-VAL
          Y
          RADIUS-VAL
          RADIUS
          AREA-VAL
          AREA
          DEPTH_M-VAL
          DEPTH_M
          RAW_DEPTH_M-VAL
          RAW_DEPTH_M
          DIAMETER_DEPTH_M-VAL
          DIAMETER_DEPTH_M
          CALIBRATED_DEPTH_M-VAL
          CALIBRATED_DEPTH_M
          DEPTH_SOURCE-VAL
          DEPTH_SOURCE
          CENTER_OFFSET_X-VAL
          CENTER_OFFSET_X
          CENTER_OFFSET_Y-VAL
          CENTER_OFFSET_Y
          POSITION_VALID-VAL
          POSITION_VALID
          CAMERA_X_M-VAL
          CAMERA_X_M
          CAMERA_Y_M-VAL
          CAMERA_Y_M
          CAMERA_Z_M-VAL
          CAMERA_Z_M
          DISTANCE_M-VAL
          DISTANCE_M
          BODY_X_M-VAL
          BODY_X_M
          BODY_Y_M-VAL
          BODY_Y_M
          BODY_Z_M-VAL
          BODY_Z_M
          BODY_DISTANCE_M-VAL
          BODY_DISTANCE_M
))