(cl:in-package cuadc_vision-msg)
(cl:export '(HEADER-VAL
          HEADER
          VALID-VAL
          VALID
          STATUS-VAL
          STATUS
          SOURCE_TOPIC-VAL
          SOURCE_TOPIC
          CLASS_NAME-VAL
          CLASS_NAME
          CONFIDENCE-VAL
          CONFIDENCE
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          CAMERA_X_M-VAL
          CAMERA_X_M
          CAMERA_Y_M-VAL
          CAMERA_Y_M
          CAMERA_Z_M-VAL
          CAMERA_Z_M
          BODY_X_M-VAL
          BODY_X_M
          BODY_Y_M-VAL
          BODY_Y_M
          BODY_Z_M-VAL
          BODY_Z_M
          ENU_EAST_M-VAL
          ENU_EAST_M
          ENU_NORTH_M-VAL
          ENU_NORTH_M
          ENU_UP_M-VAL
          ENU_UP_M
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
))